server:
  port: 8080
  address: 0.0.0.0
spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

person:
  name: Jack

description: date is 2020/12/14
name: YALM
person2:
  person-name: aa
  person-age: 22